#1.
Yes, there is a difference in the data types of the variables list_ and array_list.

The variable list_ is a Python list containing string elements. The variable array_list is a NumPy array created from the Python list, and its elements are represented as strings as well.

To print the data types of both variables, you can use the following code:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
#2.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#3.
Yes, there will be a difference in the data types of the elements present in the variables list_ and array_list after you create the array_list with the specified dtype of int.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
#4.
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

shape = num_array.shape
print("Shape of num_array:", shape)

size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
#5.
import numpy as np

zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#6.
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
print("systumm over")

systumm over
